travis:
  secure:
    BINSTAR_TOKEN: Ig5wzQGm5b9zZxGhaenKjhso1IR8SVE1eSnSEIuHSi8XeS08yvFz8ms9CF7RhxqYUlSf5TES11ri2CRS7tKoA3E/Y/nGBHbJrS5cZWjM1AJuhp1EuIy8A1SDCkrdZt/v/F/niRSFdtHpBCWnZTHhmo+/O1bFq50vJBaEgO7tFQCvij/ef5BlNYPdVBdyJHb3XJXZnO7Nop6VOwcU9/PMZmNLXl77h6Wh/IMOuDW5qKE58OvLP3a/0EKLCSOAQFCgouFtYEu8zaTmH6D2287AIJgWIiXSI9p3qmvjVqm/SW0MRTTwPYFt2SMH5lk3hIg+yPtBfF+wa2c1+fscg75I2CnWr1EBr4x8XbRzW/jGPwgbu4CBvQZIcIbyaHHKw6ojRqKMTRLxRtPlYS5Gz/0b4JJdDFmBIbWDm7n0x2z/WfONhv25ULc8+Rivdbpc3YniMnevchgCZW+d5FTXDPzYAxGAcQvRLYfShbNgc1GF505UHbC0I9Wq1gMY0boAAcBtKxpqCr+eD4Xz4E0x35c5hGIP7gpOwXtS0wBaEgIImwHXlMIMV9bY+sTht2bSz/yczL4VsV+T9mAS4dRiCDjx/fg1bJ26Crldj6KFiwRs7m1Do9OGe75+hu71NuyxwNka7zyOnJwiGowiM++QBnnfnd+p/wRFBskhEimeLPGUWvE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
